### PR TITLE
Client use case

### PR DESCRIPTION
**Pull request by shannonlnoel**

### CODE REVIEW

**Review by u19010240 — APPROVED** [review]
Looking good shan, might have to check the applicationhost.config as we've made it net 6 on dev

**Comment by u19010240** [comment]
> @u19010240 I have changed all the config back to local, being the API and the db moved to AWS because I need the work to run locally as I code the API, perhaps it is better to base another branch with your cloud config so that when I merge my code I don't wipe all the cloud configs

Yeah that might be a good idea, or maybe we sit down and show you what needs to be done to update to cloud config? Because I am able to work locally by just changing my connection string - but everything is updated to net6 [mainly the packages in applicationhost.config]

**Comment by shannonlnoel** [comment]
@u19010240 
I agree with what you saying, I am meaning developer should not be using the cloud API as the API is being developed on that branch. It should be locally run and only once we have major version releases does it get pushed to the deployment branch which would be configured to all the cloud configs

**Comment by shannonlnoel** [comment]
This PR will revert developer back to local development.
I have made a branch and added the same protection that developer has (i.e., it needs PRs to get code into it) and it has al the config that was on developer for the cloud setup.

**Pull request merged**
